@ECHO OFF
SETLOCAL

REM ----------------------------------------------------------------------------
REM Maven Wrapper Startup Script for Windows
REM ----------------------------------------------------------------------------
REM (This is a standard Maven Wrapper script. If you want the UNIX version, use mvnw)
REM
REM Licensed to the Apache Software Foundation (ASF) under one
REM or more contributor license agreements.  See the NOTICE file
REM distributed with this work for additional information
REM regarding copyright ownership.  The ASF licenses this file
REM to you under the Apache License, Version 2.0 (the
REM "License"); you may not use this file except in compliance
REM with the License.  You may obtain a copy of the License at
REM
REM   http://www.apache.org/licenses/LICENSE-2.0
REM
REM Unless required by applicable law or agreed to in writing,
REM software distributed under the License is distributed on an
REM "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
REM KIND, either express or implied.  See the License for the
REM specific language governing permissions and limitations
REM under the License.

REM ----------------------------------------------------------------------------
REM This is a minimal stub. The full Maven Wrapper scripts and jar should be
REM generated by running 'mvn -N io.takari:maven:wrapper' in your project root.
REM For now, this script will just try to call 'mvn' directly.
REM ----------------------------------------------------------------------------

where mvn >NUL 2>NUL
IF %ERRORLEVEL% EQU 0 (
  mvn %*
) ELSE (
  ECHO Maven is not installed. Please install Maven or use the full Maven Wrapper.
  EXIT /B 1
)
